# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{animalcracker}
  s.version = "0.0.1.alpha"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin 'Gus' Knowlden"]
  s.date = %q{2009-12-21}
  s.description = %q{A sweet, Sinatra-based extension library for asset hosting. Roarrrrrrrr}
  s.email = %q{gus@gusg.us}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/animalcracker.rb",
     "lib/animalcracker/asset_host.rb",
     "test/animalcracker_test.rb",
     "test/asset_host_test.rb",
     "test/file_asset_host_test.rb",
     "test/memory_asset_host_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/thumblemonks/animalcracker}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A sweet, Sinatra-based extension library for asset hosting}
  s.test_files = [
    "test/animalcracker_test.rb",
     "test/asset_host_test.rb",
     "test/file_asset_host_test.rb",
     "test/memory_asset_host_test.rb",
     "test/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<chicago>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<chicago>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<chicago>, [">= 0"])
  end
end

